name: CI/CD
on: push

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Run test
      run: pip install pytest-cov
    - name: Run test
      run: pytest --cov=time_unit timetest.py
