name: CI/CD
on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check"
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Run test
      run: pip install pytest-cov
    - name: Run test
      run: |
        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=time_unit timetest.py | tee pytest-coverage.txt
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        pip install 'setuptools>=38.6.0,<69.0' twine>=1.11.0 wheel>=0.31.0 setuptools_scm>=6.2
        python -m setuptools_scm
        python setup.py sdist bdist_wheel
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [black, build, test]
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: Set up Python
      uses: actions/setup-python@v4
    - run: |
        pip install 'setuptools>=38.6.0,<69.0' twine>=1.11.0 wheel>=0.31.0 setuptools_scm>=6.2
        python -m setuptools_scm
        python setup.py sdist bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
